import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("data/cleaned_churn_data.csv")

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x="Churn")
plt.title("Customer Churn Distribution")
plt.xlabel("Churn")
plt.ylabel("Number of Customers")
plt.tight_layout()
plt.savefig("churn_distribution.png")
plt.show()

plt.figure(figsize=(7, 4))
sns.countplot(data=df, x="Contract", hue="Churn")
plt.title("Churn by Contract Type")
plt.xlabel("Contract Type")
plt.ylabel("Number of Customers")
plt.tight_layout()
plt.savefig("churn_by_contract.png")
plt.show()

plt.figure(figsize=(7, 4))
sns.countplot(data=df, x="InternetService", hue="Churn")
plt.title("Churn by Internet Service")
plt.xlabel("Internet Service")
plt.ylabel("Number of Customers")
plt.tight_layout()
plt.savefig("churn_by_internet_service.png")
plt.show()

plt.figure(figsize=(8, 4))
sns.countplot(data=df, x="PaymentMethod", hue="Churn")
plt.title("Churn by Payment Method")
plt.xlabel("Payment Method")
plt.ylabel("Number of Customers")
plt.xticks(rotation=20)
plt.tight_layout()
plt.savefig("churn_by_payment_method.png")
plt.show()

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x="SeniorCitizen", hue="Churn")
plt.title("Churn by Senior Citizen Status")
plt.xlabel("Senior Citizen (0 = No, 1 = Yes)")
plt.ylabel("Number of Customers")
plt.tight_layout()
plt.savefig("churn_by_senior_citizen.png")
plt.show()

plt.figure(figsize=(7, 4))
sns.countplot(data=df, x="tenure_group", hue="Churn")
plt.title("Churn by Tenure Group")
plt.xlabel("Tenure Group (Months)")
plt.ylabel("Number of Customers")
plt.tight_layout()
plt.savefig("churn_by_tenure_group.png")
plt.show()
